### ISSUE TITLE
CFI generator does not correctly count empty text nodes

### ISSUE THREAD

**Issue by dmitrym0** [readium/readium-cfi-js#23]
See the original issue https://github.com/readium/readium-shared-js/issues/146

-
```html
<html>
	<p>before<a id="anchor">inside</a>after</p>
</html>
```
We should have the following results : 
**before** :  /2, /1:0, /1:6
**inside** : /2/2, /1:0, /1:6
**after** : /2, /3:0, /3:6

This specific example works with readium.

-
```html
<html>
	<p><a id="anchor">inside</a>after</p>
</html>
```
We should have results similar to the previous ones because the structure of the document didn't changes : 
**inside** : /2/2, /1:0, /1:6
**after** : /2, /3:0, /3:5

But the actual results are : 
**inside** : /2/2, /1:0, /1:6
**after** : /2, /**1**:0, /**1**:5

Note that the order isn't respected in this case : cfi("inside") > cfi("after")

-

**Problem**: Above, `after` is actually actually a 2nd text node (after the empty text node that preceeds the `<a>` element) so it should have index `3`.

cc: @danielweck @Twibit @JCCR

**Comment by danielweck** [comment]
Let's add additional unit tests here, to systematically check this "edge case" (which really isn't one ;) ):
https://github.com/readium/readium-cfi-js/blob/develop/spec/javascripts/models/cfi_generation_spec.js

**Comment by danielweck** [comment]
Question: this issue affects the CFI *generator*. What about consumption of similar CFI expressions, and the matching process against DOM trees with empty text "chunks" in mixed XML content? (which is a very common occurrence in HTML documents). I am guessing the corresponding unit tests should be added here:
https://github.com/readium/readium-cfi-js/blob/develop/spec/javascripts/models/cfi_instruction_spec.js
(sorry, I am not familiar with the fixtures setup)

**Comment by Twibit** [comment]
@danielweck i've added some tests for the cfi consumption with empty text nodes and comments. I also pushed a small fix with it.

**Comment by Twibit** [comment]
Same problem with processing instruction nodes

**Comment by JCCR** [comment]
@Twibit 
Can this be closed, or is there still an issue after #25 was merged?

**Comment by Twibit** [comment]
Yes
